### ISSUE TITLE
Maintain a pyproject.toml or a requirements.txt file to track development dependencies

### ISSUE THREAD

**Issue by stanislaw** [kamui-fin/yt2srs#14]
The development dependencies are at least:

- invoke (developer tasks)
- black (formatting)
- pytest (unit testing)
- ruff (Python linter)

It would be great to be able to install all them with one command-line command.

**Comment by kamui-fin** [comment]
I agree, I was thinking about introducing a `pipenv` setup (which can also generate `requirements.txt`) to better manage dev and runtime dependencies.

**Comment by kamui-fin** [comment]
On second thought, `Poetry` indeed looks like a better option.
