### ISSUE TITLE
Error handling when downloading YouTube videos and subtitles: Detect if a video / subtitles have been downloaded or failed

### ISSUE THREAD

**Issue by stanislaw** [kamui-fin/yt2srs#16]
Currently, if a video only has auto-generated subtitles and the fallback option is NOT enabled, the extension crashes with the following trace:

![image_2023_02_13T17_15_39_443Z](https://user-images.githubusercontent.com/452547/218572535-083e1033-dc96-480d-85dd-6a4ecc721bb0.png)

It should be possible to do full error handling when youtube-dl fails to download content. The Hooks are likely a way to go.

The issue https://github.com/kamui-fin/yt2srs/issues/5 seems to be directly related.

**Comment by kamui-fin** [comment]
Pushed a fix for this issue as well as a test. Let me know your thoughts.
