### ISSUE TITLE
Feature: System readiness check screen

### ISSUE THREAD

**Issue by stanislaw** [kamui-fin/yt2srs#24]
From https://github.com/kamui-fin/yt2srs/issues/7:

> A separate screen could show if a user has all necessary dependencies installed. At least, I have the ffmpeg and the mpv player in mind. This way the UI could present nicely if everything should work or user should still take some action.

Under the hood, the extension could run `ffmpeg -v` or `mpv -v` and ensure that some expected output is printed. Otherwise, the screen could suggest an action to a user.

**Comment by kamui-fin** [comment]
I added a probe for the ffmpeg executable and made sure it warned the user of the missing dependency. What are your thoughts?
![image](https://user-images.githubusercontent.com/65237048/218631665-6300b9df-246a-4590-9dab-907baa770c80.png)
