### ISSUE TITLE
Error in the production version of the extension: No module named "fileinput"

### ISSUE THREAD

**Issue by stanislaw** [kamui-fin/yt2srs#49]
![image_2023_02_18T11_20_36_299Z](https://user-images.githubusercontent.com/452547/220356711-ff61e88d-21aa-4638-9cf9-90cb3035f4be.png)

**Comment by stanislaw** [comment]
Just to make sure: how do you usually test the extension when you publish it? Is there a way to ensure that we run green next time? I didn't test it out myself this time but I am happy to do it next time, let me know.

**Comment by kamui-fin** [comment]
I think this is due to running a version of Anki that hasn't included the standard library completely. Which version are you on?

> how do you usually test the extension when you publish it? Is there a way to ensure that we run green next time?

For manual testing, I just download it using the code normally. Our unit tests can't pick up on these kinds of errors.
