### ISSUE TITLE
Man-made subtitles not being recognized as such, fallback to auto-generated subs throws error

### ISSUE THREAD

**Issue by linguathor** [kamui-fin/yt2srs#51]
The man-made Simplified Chinese subs for this video are not being recognized as such, and when the "fallback to auto-generated subs" option is turned on, the error copied from Anki and listed below is thrown:

https://www.youtube.com/watch?v=1kKJNLS4l1Q

( The same error occurs for this video in Traditional Chinese
https://www.youtube.com/watch?v=eoFLFsklB88 )

ERROR

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.60 (76d88073) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-03-11 14:00:00

Caught exception:
Traceback (most recent call last):
  File "C:\Users\sg\AppData\Roaming\Anki2\addons21\964531817\worker.py", line 81, in run
    result: YouTubeDownloadResult = YouTubeClient.download_video_files(
  File "C:\Users\sg\AppData\Roaming\Anki2\addons21\964531817\client_youtube.py", line 40, in download_video_files
    path_to_subtitles_file = glob(video_task.subtitle_path + "/*")[0]
IndexError: list index out of range

**Comment by shoudairika** [comment]
I wonder if you could see the decks are automatically created by this add on, could you tell me?
