### ISSUE TITLE
Add-on failed to load

### ISSUE THREAD

**Issue by m4v15** [kamui-fin/yt2srs#55]
I just upgraded to the newest anki `Version ⁨23.12.1 (1a1d4d54)⁩ Python 3.9.15 Qt 6.5.3 PyQt 6.5.3` and installed the addon, but I get add-on failed to load when I open anki. Debug info below.

> Anki 23.12.1 (1a1d4d54)  (ao)
> Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
> Platform: macOS-14.0-x86_64-i386-64bit
> 
> When loading Youtube to Anki:
> Traceback (most recent call last):
>   File "aqt.addons", line 245, in loadAddons
>   File "/Users/matt/Library/Application Support/Anki2/addons21/964531817/__init__.py", line 9, in <module>
>     from .main import launch
>   File "/Users/matt/Library/Application Support/Anki2/addons21/964531817/main.py", line 3, in <module>
>     from PyQt5 import QtCore, QtWidgets
> ModuleNotFoundError: No module named 'PyQt5'

**Comment by kamui-fin** [comment]
Fixed in latest version
