### ISSUE TITLE
Generate 0 cards in 0.0 seconds

### ISSUE THREAD

**Issue by tanhoaian01** [kamui-fin/yt2srs#57]
Hello, I'm having a problem generating cards from [this Peppa Pig episode](https://youtu.be/eje1Xi_Iu0k?si=GJRw3hO0EY91hHl2). yt-to-anki sucessfully downloaded the video (.webm) and the subtitle (.vtt) but couldn't generate cards from them. Can you please take a look and help me solve this? Thanks in advance.

## Info
Video URL: https://youtu.be/eje1Xi_Iu0k?si=GJRw3hO0EY91hHl2
Note type: https://drive.google.com/drive/folders/1YNVi7j341P1qJNd40s6GNpitO1Z7sw3s?usp=sharing
Anki: ⁨24.04.1 (ccd9ca1a)⁩
Python: 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows

## Screenshots
![yt2anki_settings](https://github.com/kamui-fin/yt-to-anki/assets/133650669/8f0cd439-4fc7-4750-9301-71f73f189659)
![yt2anki_0](https://github.com/kamui-fin/yt-to-anki/assets/133650669/fcaed19a-7eb4-4fcd-abda-144c82a35d47)

**Comment by kamui-fin** [comment]
Should be fixed now. It was just a windows API change issue with opening up ffmpeg as a subprocess.
