### ISSUE TITLE
A word of thanks and a check-in on the maintenance status

### ISSUE THREAD

**Issue by stanislaw** [kamui-fin/yt2srs#7]
Hi @kamui-fin,

Thanks for creating this extension. It is easy to use and should very well serve the needs of many language learners.

My main question: are you planning to maintain it in the future?

My story goes back to my lessons with my German language teacher, who actively uses Anki in all of his lessons. He has found your extension and wanted to try it. He could not create a deck from the YouTube videos that he tried, and he asked me if I could take a look into what was happening. I tried it as well and could not generate any deck either (my machine is macOS, my teacher has Windows).

I have cloned Anki and forked your repository, integrated your extension into Anki and started debugging it in the IDE. I have found a few issues and some of them I could already fix, but some of them require further work.

---

## Known issues

1) You bundle the extension with FFmpeg which is a great idea, but it creates a problem of having to maintain the `ffmpeg` executable binaries for at least Windows, Linux, and macOS. The bundled non-Windows binary didn't work in macOS terminal, so I had to install FFmpeg manually with `brew install ffmpeg` and remove the binaries from the extension folder. I would assume that a user could be asked to install FFmpeg/mpv and have these tools in their PATH variable.

2) I several times encountered the issue reported here: https://github.com/kamui-fin/yt2srs/issues/1 and then I figured out that you can silence but not fix this issue by setting `"no_warnings": True,` in the YouTube options. That issue seems to be related to the fact that Anki is patching `sys.stderr` with a custom error handler which does not support `istty()` and `flush()` methods. This issue needs further investigation and improved error handling because otherwise Anki UI gets stuck on the progress screen with no feedback reported to a user.

3) If a video conversion fails and for some reason the previous video is not removed, the `ffmpeg` fails with `the file already exists. do you want to overwrite it? (y/n)` leaving the Anki app hanging with no further progress. I have fixed this for now by adding `-y` to the `ffmpeg` commands. Also, the algorithm of making glob[0]... to find a downloaded video/subtitles seems to be too broad and could be reduced to avoid any collisions between the files that can also be in the folder.

4) The subtitles are parsed correctly when they are not auto-generated. When they are, the subtitles files contain more structure and lines with `<c>...</c>` tags that have to be recognized by your parser. This is something that I could consider fixing later on.

5) The code was missing formatting, linting, unit tests, and I felt like I could take it to the next level and added a few basic quality artifacts.

## Future work

- Some YouTube videos take considerable time to be downloaded. The `youtube-dl` supports a progress hook which could be used for presenting the progress indication on the User Interface.

- A separate screen could show if a user has all necessary dependencies installed. At least, I have the `ffmpeg` and the `mpv` player in mind. This way the UI could present nicely if everything should work or user should still take some action.

- When the subtitles are manually created and well-written, they can be merged together to form full sentences so that the audio files are cut sentence-by-sentence not part-by-part. This can result in a very precise cutting and therefore in a much better user experience out of the box. For automatically generated subtitles, at least a distance check can be made: If the subtitles are very close in time to each other, they can be also merged because it's likely that they are part of the same sentence spoken in the video. Both algorithms could be enabled with dedicated option checkboxes in the UI.

---

You can see my changes in the forked repo: https://github.com/stanislaw/yt2srs

My dilemma is as follows: I would like to fix the most pressing issues and release an updated extension for my teacher. Are you willing to accept all my changes via Pull Requests and update the extension, or should I go completely independently with my fork and create a new extension which I and my teacher could maintain ourselves? 

In case you would like to participate in this, could I count on your assistance and readiness to support us with timely releases of the package? I am rather inclined to continue with a fork, but I would be happy to contribute all changes back to your main repository if you have interest / resources to review all the changes and especially release the updated extension.

Please let me know what you think.

**Comment by kamui-fin** [comment]
Hey, @stanislaw. I really appreciate your contributions that have breathed new life into this addon!  

I'm sorry that I haven't been maintaining this addon for a while, as it slipped through my fingers while I was engrossed in school and other projects. I am thankful that you notified me about the current state of this addon, and I'd be happy to start maintaining it in a timely manner and review + incorporate all of your changes.

After we finish merging, I will definitely look into addressing the points in the "Future Work" section, as well as brainstorm additional ways to create a better experience for users.

**Comment by stanislaw** [comment]
Perfect! I will close this general ticket and will create separate tickets for each of the above issues.
